version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    labels:
      - "traefik.backend=home"
      - "traefik.docker.network=jitsi"
      - "traefik.enable=true"
      - "traefik.basic.port=80"
      - "traefik.basic.frontend.rule=Host:data.jiggyjigs.me"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

volumes:
  db:
  matomo:

networks:
  jitsi:
    external: true
